[package]
name = "greetings"
version = "0.1.0"
edition = "2021"
description = "Example static library project built for iOS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "greetings"
crate-type = ["staticlib"]

[dependencies]
